from table.elements import Element

PERIODS = {
    "1": [
        Element("H", RU="Водород"),
        Element("Li", RU="Литий"),
        Element("Na", RU="Натрий"),
        Element("K", RU="Калий"),
        Element("Cu", RU="Медь"),
        Element("Rb", RU="Рубидий"),
        Element("Ag", RU="Серебро"),
        Element("Cs", RU="Цезий"),
        Element("Au", RU="Золото"),
        Element("Fr", RU="Франций"),
    ],
    "2": [
        Element("Be", RU="Бериллий"),
        Element("Mg", RU="Магний"),
        Element("Ca", RU="Кальций"),
        Element("Zn", RU="Цинк"),
        Element("Sr", RU="Стронций"),
        Element("Cd", RU="Кадмий"),
        Element("Ba", RU="Барий"),
        Element("Hg", RU="Ртуть"),
        Element("Ra", RU="Радий"),
    ],
    "3": [
        Element("B", RU="Бор"),
        Element("Al", RU="Алюминий"),
        Element("Sc", RU="Скандий"),
        Element("Ga", RU="Галий"),
        Element("Y", RU="Иттрий"),
        Element("In", RU="Индий"),
        Element("La", RU="Лантан"),
        Element("Tl", RU="Таллий"),
        Element("Ac", RU="Актиний"),
    ],
    "4": [
        Element("Rf", RU="Резерфордий"),
        Element("Pb", RU="Свинец"),
        Element("Hf", RU="Гафний"),
        Element("Sn", RU="Олово"),
        Element("Zr", RU="Цирконий"),
        Element("Ge", RU="Германий"),
        Element("Ti", RU="Титан"),
        Element("Si", RU="Кремний"),
        Element("C", RU="Углерод"),
    ],
    "5": [
        Element("N", RU="Азот"),
        Element("P", RU="Фосфор"),
        Element("V", RU="Ванадий"),
        Element("As", RU="Мышьяк"),
        Element("Nb", RU="Ниобий"),
        Element("Sb", RU="Сурьма"),
        Element("Ta", RU="Тантал"),
        Element("Bi", RU="Висмут"),
        Element("Db", RU="Дубний"),
    ],
    "6": [
        Element("O", RU="Кислород"),
        Element("S", RU="Сера"),
        Element("Cr", RU="Хром"),
        Element("Se", RU="Селен"),
        Element("Mo", RU="Молибден"),
        Element("Te", RU="Теллур"),
        Element("W", RU="Вольфрам"),
        Element("Po", RU="Полоний"),
        Element("Sg", RU="Сиборгий"),
    ],
    "7": [
        Element("F", RU="Фтор"),
        Element("Cl", RU="Хлор"),
        Element("Mn", RU="Марганец"),
        Element("Br", RU="Бром"),
        Element("Tc", RU="Технеций"),
        Element("I", RU="Иод"),
        Element("Re", RU="Ренний"),
        Element("At", RU="Астат"),
        Element("Bh", RU="Борий"),
    ],
    "8": [
        Element("Fe", RU="Железо"),
        Element("Co", RU="Кобальт"),
        Element("Pd", RU="Палладий"),
        Element("Ni", RU="Никель"),
        Element("Kr", RU="Криптон"),
        Element("Ar", RU="Аргон"),
        Element("He", RU="Гелий"),
        Element("Xe", RU="Ксенон"),
        Element("Ne", RU="Неон"),
        Element("Rn", RU="Радон"),
        Element("Ds", RU="Дармштадтий"),
        Element("Mt", RU="Мейтнерий"),
        Element("Hs", RU="Хассий"),
        Element("Pt", RU="Платина"),
        Element("Ir", RU="Иридий"),
        Element("Os", RU="Осмий"),
        Element("Ru", RU="Рутений"),
    ],
}
